pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            label 'flutter-agent'
        }
    }
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'flutter pub get'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'flutter test'
            }
        }
        stage('Build APK') {
            steps {
                sh 'flutter build apk --release'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying the APK...'
                // You can add your deployment commands here
            }
        }
    }
    post {
        success {
            echo 'Build Successful'
        }
        failure {
            echo 'Build Failed'
        }
        always {
            cleanWs()
        }
    }
}
