name: Deploy to Firebase

on:
  push:
    tags:
      - 'v*'  # Trigger on version tag push (e.g., v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download APK from GitHub Releases
      id: download_apk
      uses: softprops/action-gh-release@v1
      with:
        files: 'app-release.apk'  # This is the name of the file you're downloading from the releases

    - name: Upload APK to Firebase
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        file: ${{ steps.download_apk.outputs.assets }}  # Path to the downloaded APK
        groups: testers  # Add your test groups
        releaseNotes: "Automated deploy from GitHub Actions"
