name: Firebase Deploy

on:
  push:
    tags:
      - 'v*'  # Trigger on version tag push (e.g., v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Adjust the version if necessary

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate Firebase CLI
      run: firebase use --add --token ${{ secrets.FIREBASE_TOKEN }}  # Use the Firebase token from GitHub secrets

    - name: Download APK from GitHub Releases
      id: download_apk
      uses: softprops/action-gh-release@v1
      with:
        files: 'app-release.apk'  # Specify the APK filename here

    - name: Upload APK to Firebase App Distribution
      run: |
        firebase appdistribution:distribute app-release.apk --app your-firebase-app-id --groups "testers" --release-notes "Automated deploy from GitHub Actions"
